import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const HendersonSans = localFont({
  src: [
    {
      path: "../../public/fonts/HendersonSans/HendersonSansLight.otf",
      weight: "300",
    },
    {
      path: "../../public/fonts/HendersonSans/HendersonSansBasicRegular.otf",
      weight: "400",
    },
    {
      path: "../../public/fonts/HendersonSans/HendersonSansSemiBold.otf",
      weight: "600",
    },
    {
      path: "../../public/fonts/HendersonSans/HendersonSansBasicSemiBold.otf",
      weight: "600",
    },
    {
      path: "../../public/fonts/HendersonSans/HendersonSansBasicBold.otf",
      weight: "800",
    },
  ],
  variable: "--font-henderson",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${HendersonSans.variable} ${montserrat.variable}`}>
        {children}
      </body>
    </html>
  );
}
